name: continuous_integration

on: 
  push:
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        python-version: ["3.10", "3.13"]
        exclude:
          - os: ubuntu-22.04
            python-version: "3.13"
          - os: ubuntu-24.04
            python-version: "3.10"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install charset-normalizer

  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        python-version: ["3.10", "3.13"]
        exclude:
          - os: ubuntu-22.04
            python-version: "3.13"
          - os: ubuntu-24.04
            python-version: "3.10"

    runs-on: ${{ matrix.os }}

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install charset-normalizer

      - name: Run tests with unittest
        run: python test_donations.py