name: continuous_integration

on: 
  push:
  pull_request:

jobs:

  build:
    strategy:
    matrix:
      os: [ubuntu-22.04, ubuntu-24.04]
      python-version: ["3.13"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install charset-normalizer

  test:
    strategy:
    matrix:
      os: [ubuntu-22.04, ubuntu-24.04]
      python-version: ["3.13"]

    runs-on: ${{ matrix.os }}

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install charset-normalizer

      - name: Run tests with unittest
        run: python test_donations.py