name: continuous_integration

on: 
  push:
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install charset-normalizer

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.13"]

    runs-on: ${{ matrix.os }}

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install charset-normalizer

      - name: Run tests with unittest
        run: python -m unittest test_donations.py